package org.opencoap.ssl

// AUTOGENERATED, DON'T MODIFY
internal object MbedtlsSizeOf {
    const val mbedtls_ssl_config = 368L
    const val mbedtls_entropy_context = 1032L
    const val mbedtls_ctr_drbg_context = 344L
    const val mbedtls_ssl_context = 568L
}
