#include <stdlib.h>

#include "mbedtls/ssl.h"
#include "mbedtls/ssl_cookie.h"
#include "mbedtls/x509_crt.h"

int main( void )
{
    //sizes
    printf("package org.opencoap.ssl\n\n");
    printf("// AUTOGENERATED, DON'T MODIFY\n");
    printf("internal object MbedtlsSizeOf {\n");
    printf("    const val mbedtls_ssl_config = %ldL\n", sizeof(mbedtls_ssl_config) );
    printf("    const val mbedtls_ssl_context = %ldL\n", sizeof(mbedtls_ssl_context) );
    printf("    const val mbedtls_pk_context = %ldL\n", sizeof(mbedtls_pk_context) );
    printf("    const val mbedtls_x509_crt = %ldL\n", sizeof(mbedtls_x509_crt) );
    printf("    const val mbedtls_ssl_cookie_ctx = %ldL\n", sizeof(mbedtls_ssl_cookie_ctx) );
    printf("}\n");
    printf("\n");
    printf("internal object MbedtlsOffsetOf {\n");
    printf("    const val mbedtls_x509_crt__raw = %ldL\n", offsetof(struct mbedtls_x509_crt, raw));
    printf("    const val mbedtls_x509_buf__len = %ldL\n", offsetof(struct mbedtls_asn1_buf, len));
    printf("}\n");

}
