package org.opencoap.ssl

// AUTOGENERATED, DON'T MODIFY
internal object MbedtlsSizeOf {
    const val mbedtls_ssl_config = 392L
    const val mbedtls_entropy_context = 832L
    const val mbedtls_ctr_drbg_context = 344L
    const val mbedtls_ssl_context = 568L
    const val mbedtls_pk_context = 16L
    const val mbedtls_x509_crt = 744L
    const val mbedtls_ssl_cookie_ctx = 32L
}

internal object MbedtlsOffsetOf {
    const val mbedtls_x509_crt__raw = 8L
    const val mbedtls_x509_buf__len = 8L
}
