package org.opencoap.ssl

// AUTOGENERATED, DON'T MODIFY
internal object MbedtlsSizeOf {
    const val mbedtls_ssl_config = 344L
    const val mbedtls_ssl_context = 584L
    const val mbedtls_pk_context = 568L
    const val mbedtls_x509_crt = 1296L
    const val mbedtls_ssl_cookie_ctx = 16L
}

internal object MbedtlsOffsetOf {
    const val mbedtls_x509_crt__raw = 8L
    const val mbedtls_x509_buf__len = 8L
}
