#include <stdlib.h>

#include "mbedtls/ssl.h"
#include "mbedtls/entropy.h"
#include "mbedtls/ctr_drbg.h"
#include "mbedtls/ssl_cookie.h"

int main( void )
{
    //sizes
    printf("package org.opencoap.ssl\n\n");
    printf("//AUTOGENERATED, DON'T MODIFY\n");
    printf("internal object MbedtlsSizeOf {\n");
    printf("    const val mbedtls_ssl_config = %ldL\n", sizeof(mbedtls_ssl_config) );
    printf("    const val mbedtls_entropy_context = %ldL\n", sizeof(mbedtls_entropy_context) );
    printf("    const val mbedtls_ctr_drbg_context = %ldL\n", sizeof(mbedtls_ctr_drbg_context) );
    printf("    const val mbedtls_ssl_context = %ldL\n", sizeof(mbedtls_ssl_context) );
    printf("}\n");

}
